on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Download private packages
      run: wget https://uploads.samuelprak.fr/packages/fontawesome-Ajk7mcCB3mfZGKXMpA1uGy9P6b39K5VV/fortawesome-pro.zip

    - name: Unzip private packages
      run: unzip fortawesome-pro.zip -d $GITHUB_WORKSPACE/packages

    - name: Build container image
      run: docker build -t ghcr.io/herasus/portfolio:latest .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: docker push ghcr.io/herasus/portfolio:latest

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 cluster01

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/k8s/deployment.yml
